apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: mongodb-akscs
spec:
  provider: azure
  secretObjects:
    - secretName: mongodburi    
      type: Opaque              
      data:
      - objectName: MONGODBURI
        key: MONGODBURI
  parameters:
    keyvaultName: "kv60273-akscs"       
    useVMManagedIdentity: "true"         
    userAssignedIdentityID: "dcfdb892-6ce2-4214-a38e-32c0c7c0e066" # the client ID of the MSI  
    cloudName: ""                         
    objects:   |
      array:
        - |
          objectName: MONGODBURI       
          objectType: secret              
          objectVersion: ""               
    tenantId: "449fbe1d-9c99-4509-9014-4fd5cf25b014"  
  