# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: ratings-web-ingress
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     cert-manager.io/cluster-issuer: letsencrypt
# spec:
#   tls:
#     - hosts:
#       - frontend.20-83-82-8.nip.io # IMPORTANT: update <ingress ip> with the dashed public IP of your ingress, for example frontend.13-68-177-68.nip.io
#       secretName: ratings-web-cert
#   rules:
#   - host: frontend.20-83-82-8.nip.io # IMPORTANT: update <ingress ip> with the dashed public IP of your ingress, for example frontend.13-68-177-68.nip.io
#     http:
#       paths:
#       - backend:
#           serviceName: ratings-web
#           servicePort: 80
#         path: /


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ratings-web-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/acme-challenge-type: http01
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ratings-web
            port: 
              number: 80
    host: ratingsappgw.westus2.cloudapp.azure.com # IMPORTANT: update <ingress ip> with the dashed public IP of your ingress, for example frontend.13-68-177-68.nip.io
  tls:
    - hosts:
      - ratingsappgw.westus2.cloudapp.azure.com # IMPORTANT: update <ingress ip> with the dashed public IP of your ingress, for example frontend.13-68-177-68.nip.io
      secretName: ratings-web-cert


