# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ratings-web-ingress
#   annotations:
#     kubernetes.io/ingress.class: azure/application-gateway
# spec:
#   rules:
#     - http:
#         paths:
#         - path: /
#           pathType: Prefix
#           backend:
#             service:
#               name: ratings-web
#               port: 
#                 number: 80
#     host: ratingsappgw.westus2.cloudapp.azure.com
#   tls:
#     - hosts:
#       - ratingsappgw.westus2.cloudapp.azure.com
#       secretName: aks-ingress-tls
   
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ratings-web
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  tls:
    - hosts:
      - ratingsappgw.westus2.cloudapp.azure.com
      secretName: aks-ingress-tls
  rules:
  - host: ratingsappgw.westus2.cloudapp.azure.com
    http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 80


