apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: kv60273-akscs
spec:
  provider: azure
  parameters:
    keyvaultName: "kv60273-akscs"       # The name of the Azure Key Vault
    useVMManagedIdentity: "true"         
    userAssignedIdentityID: "2caafd03-2f3f-4c6e-b52f-72f47ed1e2c5" # The clientId of the addon-created managed identity
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, Azure environment will default to AzurePublicCloud 
    objects:  
      array:
        - 
          objectName: "mongoconnection"       # In this example, 'ExampleSecret'   
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
    tenantId: "449fbe1d-9c99-4509-9014-4fd5cf25b014"               # the tenant ID containing the Azure Key Vault instance