apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aks-ingress-tls
  namespace: ratingsapp
spec:
  provider: azure
  parameters:
    # usePodIdentity: "true"
    keyvaultName: "kv60273-akscs"
    useVMManagedIdentity: "true"         
    userAssignedIdentityID: "dcfdb892-6ce2-4214-a38e-32c0c7c0e066" # the client ID of the MSI created by the 
    objects:  |
      array:
        - |
          objectName: aks-ingress-tls
          objectAlias: aks-ingress-tls
          objectType: cert
    tenantId: "449fbe1d-9c99-4509-9014-4fd5cf25b014"
  secretObjects:
    - data:
      - key: tls.key
        objectName: aks-ingress-tls # must match the name of certificate in kv
      - key: tls.crt
        objectName: aks-ingress-tls  # must match the name of certificate in kv
      secretName: aks-ingress-tls    # k8s secret manifest will be generated and synced after mounting it from pod/deploy
      type: kubernetes.io/tls
